# Serve ngApp as static files
version: '3.8'
services:
  front:
    image: 'nginx:alpine'
    ports:
      - '4200:80'
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './my-app/:/usr/share/nginx/html'
