# Serve ngApp as static files
version: '3.8'
services:
  webapp:
    image: httpd
    deploy:
      replicas: 2
    volumes:
      - './my-app/:/usr/local/apache2/htdocs/'
      - './httpd.config:/usr/local/apache2/conf/httpd.conf'
    ports:
      - "80:80"
